### PR TITLE
MAINT: Simplify pages and migrate to gh-pages based deployments

### PR DESCRIPTION
**Pull request by mmcky**
This PR: 

- [x] simplifies the companion site to basic information and code access
- [x] does **not** migrate the `code-book`
- [x] reconfigure `gh-pages` from jekyll to `gh actions` based deployments to `gh-pages`

---

The following were included in the commit history but are now **removed**.

- [x] integrates `book-dp1-public-companion` into this repo (which was responsible for building the `code-book`
- [x] setup netlify
- [x] test new repo structure with netlify
- [x] set a link back from `code-book` to the root level
- [x] check with @DrDrij that there are no jekyll powered components and `website` is fully static html
- [x] review and test the new structure with `code-book` as a built asset of the `website/code-book`
- [ ] sync then archive `book-dp1-public-companion`

### CODE REVIEW

**Comment by DrDrij** [comment]
@mmcky The codebase now looks like a static site - no Jekyll or Liquid components.

Have you got a link I can do a super quick review with? Check the site ticks all the boxes and gets the proper google ranking/social score?

**Comment by mmcky** [comment]
@HumphreyYang if you had time -- would you be able to click on the netlify deployment of this PR and click around to see if you can find any issues. It is looking pretty good to me. 

The only thing that won't work is the "Download -> BOOK" link as that file is not yet on the `main` branch. 

Screenshot 2024-02-09 at 11 50 42 am

**Comment by mmcky** [comment]
Not sure why -- but the runtimes are significantly less in this repo. 

Screenshot 2024-02-09 at 11 53 58 am

**Comment by mmcky** [comment]
@jstac after a few more quality checks I think **Step #1` is good to go for the dp book. This PR will bring everything into a single repo re: dp.quantecon.org. 

I would like to merge this on `Monday`

**Comment by HumphreyYang** [comment]
Many thanks @mmcky,

The page looks great to me.

You might have noticed this, but the view source button is not working currently:

Screenshot from 2024-02-10 14-15-18

On the live site (i.e. https://quantecon.github.io/book-dp1-public-companion/intro.html), the button is linked to a branch in the fork by `orectique`, but not the main repo:
https://github.com/orectique/book-dp1/tree/master/code-book/intro.md

I found two minor issues related to the codebook, and I have created an issue on them in the companion repo.

**Comment by mmcky** [comment]
thanks @HumphreyYang and @DrDrij for your reviews.

**Comment by mmcky** [comment]
@jstac I have updated the site based on our discussion today so we can skip the `code-book` migration all together. 

https://65c985ef37cc5587fd320af8--resonant-pie-f0089d.netlify.app/

This is the demo site of what I have put together. I will liaise with @DrDrij about a better icon for the code icon (that replaces the `code-book`). Also the links on the `Code` page won't work yet until this PR is merged as they will link directly to the GitHub directories where the code files will be.

**Comment by mmcky** [comment]
@DrDrij we are moving away from a `jupyter-book` powered code-book and towards just linking readers to a directory of files to simplify these companion pages and reduce maintenance. 

Can you recommend a more suitable icon to describes "code"?

Screenshot 2024-02-12 at 2 03 22 pm

**Comment by jstac** [comment]
Thanks @mmcky .  It will be great to see this done.  

I'm getting a 404 on the GH links. Also, this page says "Slides" https://65c985ef37cc5587fd320af8--resonant-pie-f0089d.netlify.app/code

**Comment by mmcky** [comment]
> Thanks @mmcky . It will be great to see this done.
> 
> I'm getting a 404 on the GH links. Also, this page says "Slides" https://65c985ef37cc5587fd320af8--resonant-pie-f0089d.netlify.app/code

Thanks @jstac you will get `404` on all GitHub based links until this is merged as the files are currently in the branch. 👍 

Thanks for the "slides" catch -- I'll update that now.

**Comment by mmcky** [comment]
@jstac I will merge this now --- and do a quality check of the preview with all links that will resolve. 

Then we can trigger a live update once we are happy.

**Pull request merged**
